### ISSUE TITLE
Location of Griffin sites files?

### ISSUE THREAD

**Issue by IanCodes** [pughlab/pipeline-suite#56]
Hello,

I am trying to set up the pipeline and I have got stuck with running griffin_calc_coverage.py.

Part of the error is:
`FileNotFoundError: [Errno 2] No such file or directory: '/cluster/projects/pughlab/bin/Griffin/sites/TCGA/BRCA_top_10000.txt'`

I checked the yaml file for the location of the site files, but I do not have the sites directory in the github download, nor can I find them in the repository.

TCGA_sites.yaml:
```
site_files:
  ACC: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/ACC_top_10000.txt
  BLCA: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/BLCA_top_10000.txt
  BRCA: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/BRCA_top_10000.txt
  CESC: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/CESC_top_10000.txt
  CHOL: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/CHOL_top_10000.txt
  COAD: /cluster/projects/pughlab/bin/Griffin/sites/TCGA/COAD_top_10000.txt
etc.
```

This also goes for DHS, housekeeping and TCGA sites.
Can you direct me to the site files?
Thank you.
